module.exports = {
    NULL_VALUE: "필요한 값이 없습니다.",
    OUT_OF_VALUE: "파라미터 값이 잘못 되었습니다.",
    INTERNAL_SERVER_ERROR: "서버 내부 오류",

    SIGN_UP_SUCCESS: "회원가입 성공",
    SIGN_UP_FAIL: "회원 가입 실패",
    SIGN_IN_SUCCESS: "로그인 성공",
    SIGN_IN_FAIL: "로그인 실패",
    ALREADY_ID: "존재하는 ID 입니다",
    AVAILABLE_ID : "사용가능한 ID 입니다",
    NO_ID: "가입되지 않은 이메일입니다",
    NO_USER: "일치하는 유저가 없습니다",
    MISS_MATCH_PW: "올바르지 않은 비밀번호입니다",
    PW_CHANGE_SUCCESS: "비밀번호 변경 성공",
    PW_CHANGE_FAIL: "비밀번호 변경 실패",
    USER_IMG_MISS: "유저 프로필 이미지가 필요합니다",
    FIND_PW_SUCCESS: "비밀번호 찾기 성공",
    FIND_PW_FAIL: "비밀번호 찾기 실패",
    WITHDRAW_SUCCESS: "회원 탈퇴 성공",
    WITHDRAW_FAIL: "회원 탈퇴 실패",
    WITHDRAW_USER: "탈퇴한 유저입니다",

    BOARD_CREATE_SUCCESS: "게시글 작성 성공",
    BOARD_CREATE_FAIL: "게시글 작성 실패",
    BOARD_READ_ALL_SUCCESS: "게시글 전체 조회 성공",
    BOARD_READ_ALL_FAIL: "게시글 전체 조회 실패",
    BOARD_PAGE_EXCESS: "게시글 페이지를 초과하였습니다",
    BOARD_READ_SUCCESS: "게시글 조회 성공",
    BOARD_READ_FAIL: "게시글 조회 실패",
    BOARD_UPDATE_SUCCESS: "게시글 수정 성공",
    BOARD_UPDATE_FAIL: "게시글 수정 실패",
    BOARD_DELETE_SUCCESS: "게시글 삭제 성공",
    BOARD_DELETE_FAIL: "게시글 삭제 실패",
    BOARD_RESERVE_SUCCESS: "예약 성공",
    BOARD_RESERVE_FAIL: "예약 실패",
    REVIEW_READ_SUCCESS: "리뷰 목록 조회 성공",
    REVIEW_READ_FAIL: "리뷰 목록 조회 실패",
    BOARD_EMPTY: "게시글이 없습니다",
    NO_BOARD: "존재하지 않은 게시글 입니다",
    

    SEARCH_SUCCESS: "검색 성공",
    SEARCH_FAIL: "검색 실패",

    MYPAGE_READ_SUCCESS: "마이페이지 조회 성공",
    MYPAGE_READ_FAIL: "마이페이지 조회 실패",
    MYPAGE_UPDATE_SUCCESS: "마이페이지 수정 성공",
    MYPAGE_UPDATE_FAIL: "마이페이지 수정 실패",

    X_NULL_VALUE: (x) => `${x}가 존재하지 않습니다`,
    X_CREATE_SUCCESS: (x) => `${x} 작성 성공`,
    X_CREATE_FAIL: (x) => `${x} 작성 실패`,
    X_READ_ALL_SUCCESS: (x) => `${x} 전체 조회 성공`,
    X_READ_ALL_FAIL: (x) => `${x} 전체 조회 실패`,
    X_READ_SUCCESS: (x) => `${x} 조회 성공`,
    X_READ_FAIL: (x) => `${x} 조회 실패`,
    X_UPDATE_SUCCESS: (x) => `${x} 수정 성공`,
    X_UPDATE_FAIL: (x) => `${x} 수정 실패`,
    X_DELETE_SUCCESS: (x) => `${x} 삭제 성공`,
    X_DELETE_FAIL: (x) => `${x} 삭제 실패`,  
    NO_X: (x) => `존재하지 않는 ${x} 입니다`,
    ALREADY_X: (x) => `이미 존재하는 ${x} 입니다`,
    }